import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.event.*;

/*
 * DialogoInforme.java
 *
 * Created on 6 de marzo de 2006, 09:59 AM
 */

/**
 *
 * @author  pas
 */
public class DialogoInforme extends java.awt.Frame 
{
    
    /** Creates new form DialogoInforme */
    public DialogoInforme(String titulo,String texto) 
    {
        initComponents();
        agregarEscuchas();
    	setBounds(GestionVisual.DIMENSION_STANDAR);        
    	txtImpresion.setBackground(Color.white);
    	setTitle(titulo);
    	cargarTexto(texto);
    	GestionVisual.centrar(this);                
    }
    
    
    private void cargarTexto(String texto)
    {
		txtImpresion.setText(texto);
    }
    
    private void agregarEscuchas()
    {
    	btAceptar.addActionListener(new Escucha());
    	btImprimir.addActionListener(new Escucha());
    }
    
    class Escucha implements ActionListener
    {
    	public void actionPerformed(ActionEvent e)
    	{
    		if (e.getSource()==btImprimir)
    		{
    			try
    			{
    				respuestaImprimir();
    			} catch (Exception qq)
    			{
    				;
    			}
    		}
    		if (e.getSource()==btAceptar)
    			respuestaAceptar();
    	}
    }
    
    private void respuestaAceptar()
    {
    	dispose();
    }
    
    private void respuestaImprimir()
    {
		
		JobAttributes atributos=new JobAttributes();
		atributos.setMaxPage(10);
		atributos.setSides(JobAttributes.SidesType.TWO_SIDED_SHORT_EDGE);
		
        PrintJob miPrintJob = getToolkit().
        getPrintJob( this,"",atributos,new PageAttributes() );
       	if( miPrintJob != null ) 
       	{
			Graphics graficoImpresion = miPrintJob.getGraphics();
            if( graficoImpresion != null ) 
            {
   	           txtImpresion.printAll( graficoImpresion );
   	           graficoImpresion.dispose();
            }
          	miPrintJob.end();			
		}		    	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtImpresion = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        btAceptar = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 1));

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jSplitPane1.setDividerLocation(292);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Vista de impresion"));
        txtImpresion.setEditable(false);
        jScrollPane1.setViewportView(txtImpresion);

        jPanel1.add(jScrollPane1);

        jSplitPane1.setLeftComponent(jPanel1);

        btAceptar.setText("Aceptar");
        jPanel2.add(btAceptar);

        btImprimir.setText("Imprimir");
        jPanel2.add(btImprimir);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1);

		setIconImage(Toolkit.getDefaultToolkit().getImage("recursos/imagenes/sombra.jpeg"));			

        pack();
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {
    	dispose();
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane txtImpresion;
    // End of variables declaration
    
}
