/*
 * VentanaPrincipal.java
 *
 * Created on 17 de julio de 2006, 08:45 PM
 */

/**
 *
 * @author  pas
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.table.*;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;

public class VentanaPrincipal extends javax.swing.JFrame {
    
	private String textoBenchmark,textoConsola;

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
		cargarTextos();
        initComponents();
		setearFrame();
		cargarTextos();
    }

	private void cargarTextos()
	{
		textoBenchmark="Ejecucion de pruebas de lectura y escritura de registros sobre archivos y procesamiento de resultados. Las pruebas se ejecutan mediante acceso secuencial/aleatorio sobre los registros de los archivos.";
		textoConsola="Consola para el analisis comparativo de pruebas de benchmark ejecutadas sobre diversos equipos. Proporciona gráficos e informes que facilitan la interpretación de los resultados.";
	}

    private void setearFrame()
    {
        setTitle(Main.NOMBRE+" "+Main.VERSION);
        setBounds(new Rectangle(200,100,800,600));
		setIconImage(Toolkit.getDefaultToolkit().getImage("recursos/imagenes/sombra.jpeg"));			
		setResizable(false);
        GestionVisual.centrar(this);     	
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }     

	private void actionBenchmark()
	{
		Main.mostrarVentanaBenchmark();
	}

	private void actionConsola()
	{
		Main.mostrarVentanaConsola();
	}

	private void mostrarTexto(String texto)
	{
		panel.removeAll();
		panel.add(txt);
		txt.setText(texto);
		panel.updateUI();
	}

	private void mostrarLabel()
	{
		panel.removeAll();
		panel.add(label);
		panel.updateUI();
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btBenchmark = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        btConsola = new javax.swing.JButton();
		txt=new JTextPane();
		txt.setEditable(false);

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 100));
        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(Main.NOMBRE+" "+Main.VERSION);
        jPanel2.add(jLabel1);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 20, 20));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 50));
        btBenchmark.setFont(new java.awt.Font("Dialog", 3, 22));
        btBenchmark.setForeground(new java.awt.Color(255, 255, 255));
        btBenchmark.setIcon(new javax.swing.ImageIcon("recursos/imagenes/benchmark.jpeg"));
        btBenchmark.setText("Benchmark");
        btBenchmark.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btBenchmark.setToolTipText("Modulo Benchmark");
		btBenchmark.setMnemonic('b');
		btBenchmark.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btBenchmark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarTexto(textoBenchmark);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarLabel();
            }
        });
        btBenchmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBenchmark();
            }
        });

        jPanel3.add(btBenchmark);

        panel.setLayout(new GridLayout(1,1));

        panel.setBackground(new java.awt.Color(0, 102, 102));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setIcon(new javax.swing.ImageIcon("recursos/imagenes/principal.jpeg"));
        panel.add(label);

        jPanel3.add(panel);

        btConsola.setFont(new java.awt.Font("Dialog", 3, 24));
        btConsola.setForeground(new java.awt.Color(255, 255, 255));
        btConsola.setIcon(new javax.swing.ImageIcon("recursos/imagenes/consola.jpeg"));
        btConsola.setText("Consola");
        btConsola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btConsola.setToolTipText("Modulo Consola");
		btConsola.setMnemonic('c');
		btConsola.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarTexto(textoConsola);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarLabel();
            }
        });
        btConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionConsola();
            }
        });
        jPanel3.add(btConsola);

        jSplitPane1.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane1);

        getContentPane().add(jPanel1);

		txt.setFont(new java.awt.Font("Dialog", 2, 12));

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        Main.cerrarAplicacion();
    }//GEN-LAST:event_exitForm
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBenchmark;
    private javax.swing.JButton btConsola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel;
    private javax.swing.JSplitPane jSplitPane1;
	private JTextPane txt;
    // End of variables declaration//GEN-END:variables
    
}
