package interfaz;

/**
 * Clase para testear propiedades de la clase File
 * @author  Ing. Valerio Frittelli
 * @version Marzo de 2008
 */
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class VentanaInicial extends javax.swing.JFrame {
    
    /** Creates new form VentanaInicial */
    public VentanaInicial() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jbExpl = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        explorar = new javax.swing.JMenuItem();
        propiedades = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uso de la clase File");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        jbExpl.setText("Explorar");
        jbExpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExplActionPerformed(evt);
            }
        });

        getContentPane().add(jbExpl);
        jbExpl.setBounds(100, 230, 130, 23);

        jButton2.setText("Propiedades");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(270, 230, 130, 23);

        texto.setColumns(20);
        texto.setEditable(false);
        texto.setFont(new java.awt.Font("Arial", 0, 12));
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 480, 200);

        jMenu1.setText("Archivo");
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acciones");
        explorar.setText("Explorar directorios");
        explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explorarActionPerformed(evt);
            }
        });

        jMenu2.add(explorar);

        propiedades.setText("Propiedades de un archivo");
        propiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propiedadesActionPerformed(evt);
            }
        });

        jMenu2.add(propiedades);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        about.setText("Acerca de...");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        jMenu3.add(about);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-503)/2, (screenSize.height-330)/2, 503, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
       JOptionPane.showMessageDialog(this, "Programado por: Ing. Valerio Frittelli", "Acerca de...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutActionPerformed

    private void propiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propiedadesActionPerformed
        directorio(); 
    }//GEN-LAST:event_propiedadesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        directorio();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void explorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarActionPerformed
        explorar();
    }//GEN-LAST:event_explorarActionPerformed

    private void jbExplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExplActionPerformed
        explorar();
    }//GEN-LAST:event_jbExplActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed
    
    private void explorar(){
        this.setTitle("Propiedades de un archivo");
        JFileChooser jfd = new JFileChooser();
        int r = jfd.showOpenDialog(this);
        if(r == JFileChooser.APPROVE_OPTION){
            File arch = jfd.getSelectedFile();
            if(arch != null){
                texto.setText("");
                texto.append("Propiedades del archivo: " + arch.getName());
                texto.append("\nRuta:  " + arch.getAbsolutePath());
                texto.append("\nTamaño en bytes:  " + arch.length());
                texto.append("\nOculto?:  " + arch.isHidden());
                texto.append("\nSe puede leer?:  " + arch.canRead());
            }
        }
    }
    
    private void directorio (){
        File a = new File(".");
        this.setTitle("Listado del directorio actual: " + a.getAbsolutePath());
        String [] archivos = a.list();
        if (archivos != null){
            texto.setText("");
            texto.append("Directorio actual: " + a.getAbsoluteFile() + "\n");
            for (int i=0; i<archivos.length; i++){
                File arch = new File(archivos[i]);
                texto.append("Nombre: " + arch.getName() + "\tTamano: " + arch.length() + "\n");
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem explorar;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbExpl;
    private javax.swing.JMenuItem propiedades;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
    
}
